#27: enum34 conditional requirement for poetry
ManrajGrover/py-spinners pull request #28
Opened 2019-09-20 12:19 UTC by tpinniger

## Description of new feature, or changes
similar to the changes in py-log-symbols, fix the setup.py for poetry so enum34 isn't included

@manrajgrover

2019-09-20 18:24 UTC, tpinniger commented
@manrajgrover now that all checks/tests pass can we get this merged?  
in addition can we get halo updated with this change as well -- we use halo and that is bringing in this module causing the issue with poetry.

2020-02-18 20:09 UTC, manrajgrover requested changes

2020-02-18 20:09 UTC, manrajgrover commented on requirements-dev.txt
> +astroid==1.6.5
I don't think we need this.

2020-02-18 20:20 UTC, manrajgrover commented
I think the build fails because of old setuptools version. Can you add an upgradation step in appveyor?

https://github.com/PyCQA/pylint/issues/2538#issuecomment-428840384

2020-02-19 21:30 UTC, manrajgrover approved these changes

2020-02-19 21:30 UTC, merged

2020-02-19 22:12 UTC, manrajgrover commented
@tpinniger @DylanBartels This has been released in `v0.0.24` and in halo `v0.0.29`

2020-02-19 22:12 UTC, manrajgrover commented
@tpinniger Thanks for working on this! :)

2020-02-20 13:15 UTC, tpinniger commented
My pleasure and Thanks.